// todo-react/src/Todo.js
import React, { useState, useEffect } from 'react';
import { Grid } from '@material-ui/core';
import Tittle from './components/Title';
import Logo from './components/Logo';
import Input from './components/Input';
import TodoList from './components/List/TodoList';

const Todo = () => {
  const [list, setList] = useState([]);

  useEffect(() => {
    const storageList = JSON.parse(localStorage.getItem('reactTodoList'));
    if (storageList) {
      setList(storageList);
    }
  }, []);

  const addItem = (item) => {
    const newItem = {
      id: new Date().getTime(),
      description: item,
      checked: false,
    };
    setList((prevState) => [...prevState, newItem]);
    localStorage.setItem('reactTodoList', JSON.stringify([...list, newItem]));
  };

  const removeItem = (id) => {
    const updatedList = list.filter((item) => item.id !== id);
    setList(updatedList);
    localStorage.setItem('reactTodoList', JSON.stringify(updatedList));
  };

  let todoList = null;
  if (list.length > 0) {
    todoList = <TodoList items={list} removeItem={removeItem} />;
  }

  return (
    <Grid
      container
      spacing={3}
      align="center"
      justify="center"
      direction="column"
      style={{ paddingTop: '30px' }}
    >
      <Grid item xs={12}>
        <Tittle>React To-Do list</Tittle>
      </Grid>
      <Grid item xs={12}>
        <Logo />
      </Grid>
      <Grid item xs={12}>
        <Input addItem={addItem} />
      </Grid>
      <Grid item xs={12}>
        {todoList}
      </Grid>
    </Grid>
  );
};

export default Todo;

// todo-vue/src/components/Todo.vue
<template>
  <v-container>
    <v-row class="text-center pt-5">
      <app-title title="Vue To-Do list"></app-title>
      <app-logo></app-logo>
      <app-input @newTask="addTask"></app-input>
      <app-list :tasks="tasks" @removeTask="removeTask"></app-list>
    </v-row>
  </v-container>
</template>

<script>
import Logo from './Logo.vue';
import Title from './Title.vue';
import Input from './Input.vue';
import List from './TodoList/List.vue';

export default {
  components: {
    appLogo: Logo,
    appTitle: Title,
    appInput: Input,
    appList: List,
  },
  data() {
    return {
      tasks: [],
    };
  },
  created() {
    this.tasks = [...JSON.parse(localStorage.getItem('vueTodoList'))];
  },
  methods: {
    addTask(task) {
      const id = new Date().getTime();
      this.tasks.push({ id, description: task, checked: false });
      localStorage.setItem('vueTodoList', JSON.stringify([...this.tasks]));
    },
    removeTask(id) {
      const index = this.tasks.findIndex((task) => task.id === id);
      if (index >= 0) {
        this.tasks.splice(index, 1);
        localStorage.setItem('vueTodoList', JSON.stringify([...this.tasks]));
      }
    },
  },
};
</script>

<style></style>
